### ISSUE TITLE
Certificate backward transfers limits

### ISSUE THREAD

**Issue by albertog78** [HorizenOfficial/Sidechains-SDK#113]
In mainchain different limitations are applied to txs and certificates. For example it is limited the total number of some opcodes (eg. OP_CHECKSIG) specified in inputs and outputs and this limitation applies also to certificate if we use P2PKH scripts in backward transfers. Obviously other limitations could be applied like MAX_TX_SIZE. 
Given that, we must avoid generating an invalid certificate otherwise it will not be accepted in MC and then the sidechain is going to be ceased. For this reason we should identify a strategy for selecting backward transfers up to a certain limit (to simplify we will include up to a certain number of BTs in a certificate that guarantees that the certificate will meet the MC rules.

**Comment by i-Alex** [comment]
Limit of at most 3999 BTs per certificate was added as a part of https://github.com/HorizenOfficial/Sidechains-SDK/pull/458
Works for both UTXO and Account model.
