### ISSUE TITLE
Create a new sidechain

### ISSUE THREAD

**Issue by Cermelli** [HorizenOfficial/Sidechains-SDK#151]
**HDE task**

Starting points:

- https://github.com/HorizenOfficial/Sidechains-SDK/blob/master/README.md
- https://github.com/HorizenOfficial/zend_oo/blob/sidechains_testnet/README.md

Required steps:
- Build zend_oo and Sidechain SDK
- Declare a sidechain
- Start a sidechain node
- Perform a Forward Transfer from the mainchain to the sidechain
- Perform a transfer inside the sidechain
- Perform a Withdrawal Request from the sidechain
- Obtain coins back to the mainchain
- Produce a detailed report that includes the commands used during the test (inputs, outputs, … )
Please note: the report can be submitted in various ways. We're also in the process of adding file attachment support to our bounty claim form - there it will be possible to upload your report in .pdf, .docx or .md. For the time being, please submit the report by providing a link to a document, either a private gist, markdown file in a private repo or a Google Docs.
- Include any feedback you might have related to your test (recommendations, areas of improvements, …)

**For more info:** https://hde.horizen.global/tasks
***This bounty will be paid to the first 10 contributors submitting a report meeting our quality standards

**Comment by morganblack25** [comment]
hola
comoa  estado :D

**Comment by jtoownus** [comment]
Hey @morganblack25 ,
if possible, please keep discussions in English so everybody can follow along. Thank you :)

**Comment by wawanz001** [comment]
What is this?

**Comment by minbinL** [comment]
Do we have 10 accepted participants now??

**Comment by jtoownus** [comment]
@minbinL not yet. You interested?

**Comment by jedidefault** [comment]
I am interested. :)

**Comment by aaron008** [comment]
Hello,
I have been looking over the documentation, but I do not see how to send the detailed report for submission.

**Comment by angievi** [comment]
Hello @aaron008 , have you read the following links?

https://github.com/ZencashOfficial/Sidechains-SDK/blob/master/readme.md
https://github.com/ZencashOfficial/zend_oo/blob/sidechains_testnet/README.md

Let me know how else I can help, regards!

**Comment by aaron008** [comment]
Hello @angievi, thank you for your reply.  Maybe I was not clear enough in my comment. 
According to the required steps above:
"Produce a detailed report that includes the commands used during the test (inputs, outputs, … )"
"Include any feedback you might have related to your test (recommendations, areas of improvements, …)"

Nowhere in the links does it state how to submit the "detailed report".
How do you know I have done all the steps outline above?
Where do we provide feedback about the related test?
Some of the steps listed above need more explanation. (The first 7 bullet points are documented)

Also, please assume that the documentation/links were read which is stated clearly in the tasks.

**Comment by jtoownus** [comment]
Hey @aaron008 
sorry for the confusion. The detailed report can be submitted in various ways. We're in the process of adding file attachment support to our bounty claim form. There you would be able to upload your report in .pdf, .docx or .md.

You can also submit the report by providing a link to a document, either a private gist, markdown file in a private repo or a google doc.

We assume we will know from your report if you actually went through all the steps. If it includes valid and valuable feedback the contributor will most likely have gone through the entire process.

Hope that helps, for any further questions please comment:)

**Comment by rickmort** [comment]
Is this task still available?

**Comment by angievi** [comment]
Hello @rickmort yes, it is still open and you can work on it, if you want to start working on it just let us know here in the comments :) 

Thank you!

**Comment by xgarreau** [comment]
Hi there !

I just completed 3 blog posts documenting : 
- Installing Zendoo and basic use of it
- Installing Sidechains SDK and using it to configure and start a sidechain node
- Performing transfers (Forward, Backward and inside the sidechain)

Here are the links :
- https://mescryptos.fr/les-sidechains-horizen-le-noeud-zend-oo/
- https://mescryptos.fr/les-sidechains-horizen-ma-premiere-sidechain/
- https://mescryptos.fr/les-sidechains-horizen-transfert-de-zen/

There are 2 bonus parts dealing with the Faucet and Node hosting at pecunia.

Not sure if I can claim a bounty though as it's written in French.

Best Regards.
Xavier

**Comment by kimyaci8674** [comment]
veryy good project..

**Comment by rosariopabst** [comment]
> Hi there !
> 
> I just completed 3 blog posts documenting :
> 
> * Installing Zendoo and basic use of it
> * Installing Sidechains SDK and using it to configure and start a sidechain node
> * Performing transfers (Forward, Backward and inside the sidechain)
> 
> Here are the links :
> 
> * https://mescryptos.fr/les-sidechains-horizen-le-noeud-zend-oo/
> * https://mescryptos.fr/les-sidechains-horizen-ma-premiere-sidechain/
> * https://mescryptos.fr/les-sidechains-horizen-transfert-de-zen/
> 
> There are 2 bonus parts dealing with the Faucet and Node hosting at pecunia.
> 
> Not sure if I can claim a bounty though as it's written in French.
> 
> Best Regards.
> Xavier

@xgarreau Great job! Feel free to go through the bounty claim process.

**Comment by xgarreau** [comment]
Hi !

Thank you very much @rosariopabst I'm glad you appreciated the tutorials.

I went through the bounty claim process. I hope it worked.

I created an account on HDE with github, joined HEAP, fill my profile and claimed bounty here https://hde.horizen.global/account/claim-bounty for sidechains SDK, issue 151 with PR 169, i filled my postal and zen addresses and submitted the form.

I got a popup saying it will be under review and that I should be contacted by email. But the "claimed bounties" section of my HDE profile is empty, so I'm not actually sure all went well. Perhaps it only shows up when validated. Maybe it would be a good idea to add under review claims as well ?

BTW, thank you for HDE and bounties. That's a great thing for the community.

**Comment by erazhu31** [comment]
Hi Is this task still available?

**Comment by angievi** [comment]
Hello @erazhu31  yes, it is still open and you can work on it, if you want to start working on it just let us know here in the comments :)

Thank you!

**Comment by erazhu31** [comment]
Hi @angievi i will start then thanks

**Comment by erazhu31** [comment]
Hello @angievi   completed , i went through the whole process i followed those tutorials links:

https://mescryptos.fr/les-sidechains-horizen-le-noeud-zend-oo/
https://mescryptos.fr/les-sidechains-horizen-ma-premiere-sidechain/
https://mescryptos.fr/les-sidechains-horizen-transfert-de-zen/
https://github.com/HorizenOfficial/Sidechains-SDK/blob/b689690908e821d1039d8617e384622c36b02e69/examples/simpleapp/mc_sc_workflow_example.md

this is my last block 
 curl -X POST "http://127.0.0.1:9085/block/generate" -H "accept: application/json"  -d "{\"epochNumber\":2,\"slotNumber\":5}"
{
  "result" : {
    "blockId" : "3dab08a4485e0269f260fc4777b253061ebd86b849c917f9edf3dd8e9139280d"
  }
and this is my sidechain end balance 
curl -X POST "http://127.0.0.1:9085/wallet/balance" -H "accept: application/json"
{
  "result" : {
    "balance" : 43600000000
  }
}

Where should i link my report to
Thanks

**Comment by angievi** [comment]
Hi @erazhu31 , you can provide the link to your report here. We will review and get back to you shortly. thank you!

**Comment by erazhu31** [comment]
HI @angievi  here in my report : https://github.com/erazhu31/horizen-sidechain/blob/master/README.md

**Comment by angievi** [comment]
Hey @erazhu31 we have reviewed your report and it complies with our quality standards! Please follow the bounty claim process here: https://hde.horizen.global/landing-page/bounty-payout-policy . Please, let me know when you claim your bounty for awareness, thanks!

**Comment by angievi** [comment]
> Hi !
> 
> Thank you very much @rosariopabst I'm glad you appreciated the tutorials.
> 
> I went through the bounty claim process. I hope it worked.
> 
> I created an account on HDE with github, joined HEAP, fill my profile and claimed bounty here https://hde.horizen.global/account/claim-bounty for sidechains SDK, issue 151 with PR 169, i filled my postal and zen addresses and submitted the form.
> 
> I got a popup saying it will be under review and that I should be contacted by email. But the "claimed bounties" section of my HDE profile is empty, so I'm not actually sure all went well. Perhaps it only shows up when validated. Maybe it would be a good idea to add under review claims as well ?
> 
> BTW, thank you for HDE and bounties. That's a great thing for the community.

Hey @xgarreau have you claimed your bounty? Please make sure you are following the steps listed here: https://hde.horizen.global/landing-page/bounty-payout-policy , let me know if you have any questions please :) thank you!

**Comment by erazhu31** [comment]
Hi @angievi I just went through 
Thanks

**Comment by erazhu31** [comment]
Hi @angievi  i claimed the bounty and filled the form. I  received an confirmation email but since i have no transaction on my adr
could you please confirm thanks

**Comment by angievi** [comment]
Hey @erazhu31 sure, will come back to you with an answer! Thank you!

**Comment by erazhu31** [comment]
Hi @angievi received Thanks

**Comment by gootecks** [comment]
Hey there, is this still open?

**Comment by rosariopabst** [comment]
Hi @gootecks it is and would like to see your blockers/issues when you submit the completion.

**Comment by gootecks** [comment]
> Hi @gootecks it is and would like to see your blockers/issues when you submit the completion.

Great, I'm on it and will add blockers/issues in the report.  First time trying this, so I'm starting with the test sidechain task and will tackle this afterwards.

**Comment by luisantoniocrag** [comment]
Hey! Can I still participate in this task?

**Comment by angievi** [comment]
> Hey! Can I still participate in this task?

Hi! yes you can still create a sidechain :) please provide your report and let us know if you have any questions, thank you!

**Comment by Mlhozgr** [comment]
Hey! Is this task still avaible?

**Comment by infinitEnigma** [comment]
Hi, same question, is this task still available?

**Comment by infinitEnigma** [comment]
> Hi, same question, is this task still available?

[**if so, here is my report** 💯](https://github.com/infinitEnigma/HorizenSideChains_test/tree/main/Create%20a%20new%20sidechain%20%23151)
@angievi 🎉

**Comment by angievi** [comment]
Hello @Mlhozgr yes, you can still create a sidechain :) please provide your report when completed, thanks!

**Comment by angievi** [comment]
> > Hi, same question, is this task still available?
> 
> [**if so, here is my report** 💯](https://github.com/infinitEnigma/HorizenSideChains_test/tree/main/Create%20a%20new%20sidechain%20%23151)
> @angievi 🎉

great! it is currently under review, I'll come back to you with feedback thanks!

**Comment by luisantoniocrag** [comment]
Hey @angievi. There is my report: https://github.com/luisantoniocrag/create-a-new-sidechain

Thank you =)

**Comment by angievi** [comment]
thank you @luisantoniocrag , it is currently under review!

**Comment by mzaghab** [comment]
Hi @angievi, is this task still available?

**Comment by neiithanlv** [comment]
I wanna participate in this task!!!

**Comment by angievi** [comment]
Yes, this task is still available. You can still create a sidechain @mzaghab and @neiithanlv please provide your reports :) thanks!

**Comment by angievi** [comment]
> > > Hi, same question, is this task still available?
> > 
> > 
> > [**if so, here is my report** 💯](https://github.com/infinitEnigma/HorizenSideChains_test/tree/main/Create%20a%20new%20sidechain%20%23151)
> > @angievi 🎉
> 
> great! it is currently under review, I'll come back to you with feedback thanks!

Hi @infinitEnigma , your contribution has been approved. Please fill the bounty form again if you wish for the bounty to be sent to a different address.  https://hde.horizen.global/landing-page/bounty-payout-policy thanks!

**Comment by infinitEnigma** [comment]
> > > > Hi, same question, is this task still available?
> > > 
> > > 
> > > [**if so, here is my report** 💯](https://github.com/infinitEnigma/HorizenSideChains_test/tree/main/Create%20a%20new%20sidechain%20%23151)
> > > @angievi 🎉
> > 
> > 
> > great! it is currently under review, I'll come back to you with feedback thanks!
> 
> Hi @infinitEnigma , your contribution has been approved. Please fill the bounty form again if you wish for the bounty to be sent to a different address. https://hde.horizen.global/landing-page/bounty-payout-policy thanks!

Thank you @angievi, I would like to use the address I have already provided, if that is ok.

**Comment by Andreas2000** [comment]
Hi @angievi 
Is this task available for a bounty claim?
Thanks

**Comment by mzaghab** [comment]
Hi all,
I have a problem when trying to make a forward transfert and validate it, but i am not sure if I mess a step or if it's a bug 
- I follow all the steps for the creation of Build zend_oo and Sidechain SDK, Declare my sidechain, Start my sidechain node, make a transaction and mine it on the mainchain, but on the sidechain when I try to validate and mine the transaction I have the error below, any idea please :
```
curl -X POST "http://127.0.0.1:9085/block/forgingInfo" -H "accept: application/json" -H "Content-Type: application/json"
````
result
```
{
  "result" : {
    "consensusSecondsInSlot" : 120,
    "consensusSlotsInEpoch" : 720,
    "bestEpochNumber" : 1,
    "bestSlotNumber" : 720
  }
```
and 
```
curl -X POST "http://127.0.0.1:9085/block/generate" -H "accept: application/json"  -H "Content-Type: application/json" -d '{"epochNumber":2,"slotNumber":1}'

```
Error 
```
{
  "error" : {
    "code" : "0105",
    "description" : "Block was not created: Slot had been skipped",
    "detail" : ""
  }
}
```

**Comment by infinitEnigma** [comment]
> * I follow all the steps for the creation of Build zend_oo and Sidechain SDK, Declare my sidechain, Start my sidechain node, make a transaction and mine it on the mainchain, but on the sidechain when I try to validate and mine the transaction I have the error below, any idea please :
if u are on windows then the issue maybe is in the binaries u are using. @mzaghab

**Comment by mzaghab** [comment]
hi @infinitEnigma, thank's for your help, but I mounted a linux vm with ubuntu 18.4, 
will try with other ubuntu versions and os

**Comment by infinitEnigma** [comment]
> hi @infinitEnigma, thank's for your help, but I mounted a linux vm with ubuntu 18.4,
> will try with other ubuntu versions and os

it worked on this Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-130-generic x86_64) (VM)

**Comment by mzaghab** [comment]
thanks @infinitEnigma, i had to move to ubuntu 18.4 LTS Desktop version to be able to pass this problem, i had the issue with ubuntu version 18.4 and 20.4 server
@angievi this is my report, tell if it's eligible for the bounty claim 👍 
https://github.com/mzaghab/my-horizen/tree/main/task-151

**Comment by angievi** [comment]
> Hi @angievi
> Is this task available for a bounty claim?
> Thanks

Hi @Andreas2000 yes, you can still create a sidechain following the steps listed above! thanks :)

**Comment by angievi** [comment]
> thanks @infinitEnigma, i had to move to ubuntu 18.4 LTS Desktop version to be able to pass this problem, i had the issue with ubuntu version 18.4 and 20.4 server
> @angievi this is my report, tell me if it's eligible for the bounty claim 👍
> https://github.com/mzaghab/my-horizen/tree/main/task-151

Thank you @mzaghab your contribution is being reviewed, I'll come back to you in the next few days, thanks for contributing!

**Comment by rickmort** [comment]
@angievi 

Here I share my report: https://github.com/rickmort/hde-create-new-sidechain/blob/main/README.md

Thank you!

**Comment by muberraa** [comment]
Hey there, is this test still open?

**Comment by francov99** [comment]
Hi @angievi 
Done.
I share my report
https://github.com/francov99/task-create-new-sidechain

Thank you 😀

**Comment by menuc** [comment]
Can I still apply for this task?

**Comment by mzaghab** [comment]
> > thanks @infinitEnigma, i had to move to ubuntu 18.4 LTS Desktop version to be able to pass this problem, i had the issue with ubuntu version 18.4 and 20.4 server
> > @angievi this is my report, tell me if it's eligible for the bounty claim 👍
> > https://github.com/mzaghab/my-horizen/tree/main/task-151
> 
> Thank you @mzaghab your contribution is being reviewed, I'll come back to you in the next few days, thanks for contributing!

Hi @angievi any news about my contribution review ?

**Comment by angievi** [comment]
Hi @mzaghab @francov99 @rickmort can you please fill the bounty form here: https://hde.horizen.global/landing-page/bounty-payout-policy thanks!

**Comment by angievi** [comment]
hello @muberraa and @menuc yes , there is still place for you both to participate in this HDE task
Please provide your report with the format indicated in the instructions, thanks!

**Comment by angievi** [comment]
> Hey @angievi. Here's my report: https://github.com/luisantoniocrag/create-a-new-sidechain
> 
> Thank you =)

Hello @luisantoniocrag , can you please fill your info to claim the bounty:  https://hde.horizen.global/landing-page/bounty-payout-policy thanks!

**Comment by muberraa** [comment]
> hello @muberraa and @menuc yes , there is still place for you both to participate in this HDE task
> Please provide your report with the format indicated in the instructions, thanks!

hi @angievi I will start today thanks

**Comment by rickmort** [comment]
Sure @angievi! Thank you.

**Comment by muberraa** [comment]
Hi Angie! https://github.com/muberraa/zendooSidechain

> hello @muberraa and @menuc yes , there is still place for you both to participate in this HDE task
> Please provide your report with the format indicated in the instructions, thanks!

Hi again @angievi . Here is my report. https://github.com/muberraa/zendooSidechain

**Comment by menuc** [comment]
> hello @muberraa and @menuc yes , there is still place for you both to participate in this HDE task
> Please provide your report with the format indicated in the instructions, thanks!

https://github.com/menuc/zendooSidechainWindows/blob/main/README.md
this is my docs,Thank u.

**Comment by angievi** [comment]
thank you @menuc , It will be reviewed and I'll come back to you in the following days with feedback.
have a great day!

**Comment by Mlhozgr** [comment]
Hi @angievi . I tried to complete this task in two  different OS.(Linux Mint and Ubuntu 20.04).When i try to do ./src/zend -regtest -websocket this step system says there is no zend file in src.I tried many times with different OS.But same result. I will try with Elemantry OS but i am wondering has anybody encountered or reported a problem similar to the one I have encountered? I have been trying to find a solution for 2 weeks but have not solved it in any way.

**Comment by muberraa** [comment]
Hi @angievi ,
You returned in the message above @menuc. There is no problem with my report, right?

> thank you @menuc , It will be reviewed and I'll come back to you in the following days with feedback.
> have a great day!

**Comment by infinitEnigma** [comment]
> Hi @angievi . I tried to complete this task in two different OS.(Linux Mint and Ubuntu 20.04).When i try to do ./src/zend -regtest -websocket this step system says there is no zend file in src.I tried many times with different OS.But same result. I will try with Elemantry OS but i am wondering has anybody encountered or reported a problem similar to the one I have encountered? I have been trying to find a solution for 2 weeks but have not solved it in any way.

it works on Ubuntu 20.04, u should build first with: `./zcutil/build.sh -j$(nproc)`, when build is done, run: `./zcutil/fetch-params.sh`, and  then: `./src/zend -...`

**Comment by Mlhozgr** [comment]
> > Hi @angievi . I tried to complete this task in two different OS.(Linux Mint and Ubuntu 20.04).When i try to do ./src/zend -regtest -websocket this step system says there is no zend file in src.I tried many times with different OS.But same result. I will try with Elemantry OS but i am wondering has anybody encountered or reported a problem similar to the one I have encountered? I have been trying to find a solution for 2 weeks but have not solved it in any way.
> 
> @Mlhozgr it works on Ubuntu 20.04, u should build first with: `./zcutil/build.sh -j$(nproc)`, when build is done, run: `./zcutil/fetch-params.sh`, and then: `./src/zend -...`

Actually i did all steps.But it doesnt work. Yesterday i tried on ElemantryOS. But still doesnt work. I stuck. this problem made me mad.

**Comment by mrltndl** [comment]
Hi @angievi
Is this task available?
Thanks...

**Comment by angievi** [comment]
> Hi @angievi ,
> You returned in the message above @menuc. There is no problem with my report, right?
> 
> > thank you @menuc , It will be reviewed and I'll come back to you in the following days with feedback.
> > have a great day!

Hi @muberraa , your report is also being reviewed, I'll come back to you with feedback.

Thanks!

**Comment by angievi** [comment]
Hello everyone, this issue has also reached the number of participants allowed, thanks for contributing to HDE!

**Comment by infinitEnigma** [comment]
Hi @angievi, I received only half of the bounty rewards, 20 days ago. When will I get the rest? Thanks.

**Comment by angievi** [comment]
> Hi @angievi, I received only half of the bounty rewards, 20 days ago. When will I get the rest? Thanks.

You are right @infinitEnigma , will send the rest shortly. Posting here the txid for reference: https://explorer.horizen.io/tx/f274cad19fb79b736969890f6747374586d5dd1493bd592b3815064591cb7a33

**Comment by rickmort** [comment]
> Hi @angievi, I received only half of the bounty rewards, 20 days ago. When will I get the rest? Thanks.

You sent me $ZEN for only a bounty to, do I have to wait for the next payment cycle? By the way, thanks a lot @angievi!

**Comment by angievi** [comment]
> > Hi @angievi, I received only half of the bounty rewards, 20 days ago. When will I get the rest? Thanks.
> 
> You sent me $ZEN for only a bounty to, do I have to wait for the next payment cycle? By the way, thanks a lot @angievi!

did you fill the bounty form again for this issue? 

> @angievi
> 
> Here I share my report: https://github.com/rickmort/hde-create-new-sidechain/blob/main/README.md
> 
> Thank you!

did you fill the bounty form again for this issue? I think Please submit again, thank you! https://hde.horizen.global/landing-page/bounty-payout-policy

**Comment by rickmort** [comment]
> > > Hi @angievi, I received only half of the bounty rewards, 20 days ago. When will I get the rest? Thanks.
> > 
> > 
> > You sent me $ZEN for only a bounty to, do I have to wait for the next payment cycle? By the way, thanks a lot @angievi!
> 
> > @angievi
> > Here I share my report: https://github.com/rickmort/hde-create-new-sidechain/blob/main/README.md
> > Thank you!
> 
> did you fill the bounty form again for this issue? I think Please submit again, thank you! https://hde.horizen.global/landing-page/bounty-payout-policy

Sure, already sent again, thanks!

**Comment by Mlhozgr** [comment]
> Hi @angievi . I tried to complete this task in two different OS.(Linux Mint and Ubuntu 20.04).When i try to do ./src/zend -regtest -websocket this step system says there is no zend file in src.I tried many times with different OS.But same result. I will try with Elemantry OS but i am wondering has anybody encountered or reported a problem similar to the one I have encountered? I have been trying to find a solution for 2 weeks but have not solved it in any way.

@angievi I wonder why you ignored me.  I am getting an error about the project and I am asking a related question.  But you respond to other people and frankly ignore my message.  How do you expect people to contribute to the project this way?

**Comment by angievi** [comment]
Hello @muberraa and @menuc , can you please fill out the bounty form: https://hde.horizen.global/landing-page/bounty-payout-policy

**Comment by angievi** [comment]
Thank you everyone that contributed to this HDE issue! We have reached the number of participants allowed.

**Comment by angievi** [comment]
> > Hi @angievi . I tried to complete this task in two different OS.(Linux Mint and Ubuntu 20.04).When i try to do ./src/zend -regtest -websocket this step system says there is no zend file in src.I tried many times with different OS.But same result. I will try with Elemantry OS but i am wondering has anybody encountered or reported a problem similar to the one I have encountered? I have been trying to find a solution for 2 weeks but have not solved it in any way.
> 
> @angievi I wonder why you ignored me. I am getting an error about the project and I am asking a related question. But you respond to other people and frankly ignore my message. How do you expect people to contribute to the project this way?

Hi @Mlhozgr, sorry for not being able to reply sooner. Seems that you are no able to compile, I escalated this issue with the infra team and we suggest you to do it in Ubuntu 18.04. I invite you to participate in upcoming HDE tasks as this one has reached the number of participants allowed. 

regards,

Angie.

**Comment by rickmort** [comment]
Just to confirm.
will I receive the payment? I see that the issue is already closed.
@angievi

**Comment by menuc** [comment]
@angievi hi,When can I pay?
