### ISSUE TITLE
Fix ApplicationNodeViewProvider

### ISSUE THREAD

**Issue by oaleksandrov-ip** [HorizenOfficial/Sidechains-SDK#154]
current function for ApplicationNodeViewProvider is  public Try<SidechainNodeView> getSidechainNodeView();
This is an incorrect way, returning sidechainNodeView is not multithreading save, instead, it shall provide a way to pass a function to be executed over SidechainNodeView

**Comment by i-Alex** [comment]
Solved in the PR https://github.com/HorizenOfficial/Sidechains-SDK/pull/157
