### ISSUE TITLE
SCBootstrappingTool genesisinfo command arguments currupted

### ISSUE THREAD

**Issue by i-Alex** [HorizenOfficial/Sidechains-SDK#158]
genesisinfo command arguments can be too long for some platforms.
For example, on windows cmd max line length is 8192, but the command with arguments is about 8600, so the last ~400 symbols were cut from the command.
Currently bootstrapping tool accept only single-line commands. We need to add the support of multi line arguments.

**Comment by megaluck** [comment]
Hi @i-Alex  i run into the same problem on Windows, this is how I was able to circumvent 

created a txt file with the whole command  and passed the file as a input , give it a try 

**ex:**

`java -jar tools/sctool/target/Sidechains-SDK-ScBootstrappingTools-0.2.1.jar < genesis.txt
`

**Comment by i-Alex** [comment]
Solved in the PR https://github.com/HorizenOfficial/Sidechains-SDK/pull/172
