### ISSUE TITLE
wallet storage not updated correctly with box having custom proposition

### ISSUE THREAD

**Issue by paolocappelletti** [HorizenOfficial/Sidechains-SDK#184]
**Issue:**
the API endpoint /allBoxes does not show boxes owned by the user that have custom proposition.
(for example CarSellOrderBox  in the LamboRegistry app)

**Cause:**
SidechainWallet  uses this code to check if a box can be opened by the user:
 pubKeys.contains(box.proposition())
(see: [here](https://github.com/HorizenOfficial/Sidechains-SDK/blob/master/sdk/src/main/scala/com/horizen/SidechainWallet.scala#L121) )
This relies on the the .equals() method of the Proposition class, but this can cause a failing check if the box has a custom proposition that overrides the equals method (as in the case of the [SellOrderProposition  ](https://github.com/HorizenOfficial/lambo-registry/blob/master/src/main/java/io/horizen/lambo/car/proposition/SellOrderProposition.java#L95)of CarSellOrderBox  in the lamboregistry)

**Proposed solution:**
exend the Proposition interface with a new method 
`public boolean matches(Proposition otherProposition)`
and modifiy the SidechainWallet  to use it  for the box-owning check.

**Comment by i-Alex** [comment]
Thanks! I agree with the proposal.

**Comment by i-Alex** [comment]
The proposed changes are not fully enough for us. We should review the way how we store secrets and retrieve secrets for given proposition. The corner case is shown by the SellOrderProposition, which is actually a complex Proposition, that can have multiple related Secrets.

**Comment by paolocappelletti** [comment]
this bug afftects also the  getNodeWallet().boxesOfType(...) method of SidechainNodeView : it does not  returns the boxes locked by a custom proposition
