### ISSUE TITLE
add Box property to discriminate standard box from custom box

### ISSUE THREAD

**Issue by paolocappelletti** [HorizenOfficial/Sidechains-SDK#186]
**Issue:** 
Custom user-defined box type ids can overlap with standard ones, but we need to discriminate them.
For example in the lambo registry app the CarBox has typeId = 1 , the same  as the standard RegularBox : due to this the following code is not enough to select only the boxes of type CarBox:

```java
if (currentBox.boxTypeId() == CarRegistryBoxesIdsEnum.CarBoxId.id()) {
  ...
}
```

furthermore, in the **wallet/allBoxes** endpoint result list is not very clear the difference between the two elements:
```json

           {
               "typeId": 1,
               "value": 42000,
               "nonce": 2832492057234175154,
                "id": "ac54c0dc93e6cecb4e6cb80efd817b878d9027fca5e2cce14b79b5ec92e0115e",
                "proposition": {
                    "publicKey": "4a2437a1106a9b5912dfc2162180fe5758cfe449f45c72bfdee7ad928a570c0e"
                }
            },
            {
                "typeId": 1,
                "year": 2018,
                "color": "Red",
                "vin": "QWEFGFWRGWSGWR341",
                "model": "Lamborghini Aventador",
                "nonce": 4173182523242333935,
                "id": "52c120fbe847e9864c8ccad7f27a7cd0f2d1cb38ce7646bb17133c0879425595",
                "proposition": {
                    "publicKey": "4a2437a1106a9b5912dfc2162180fe5758cfe449f45c72bfdee7ad928a570c0e"
                }
            }`
```
**Possible solution:**
We need a new  boolean property on the Box interface to discriminate the default box types from the custom ones.
The property should be returned also in the **wallet/allBoxes** endpoint result list.

**Comment by i-Alex** [comment]
It's allowed to keep the same type ids between core types and custom types. The only restriction is that core type ids must be unique between themselves. And the same between custom types. We need it for serialization.

I agree with you, that it's confusing to see such case as you described, so additional boolean property can be a good solution here.

**Comment by i-Alex** [comment]
Add 2 fields in json:
1) "typeName" : <class name>, like "ZenBox"
2) isCustom: true | false
Remove:
1) "typeId" from json, use only for internal byte serialization needs.
Note: check the usage of type id in gamechain, lambo and zkAudit.

**Comment by i-Alex** [comment]
Done
