### ISSUE TITLE
IODBStorageUtil.getStorage should accept the other optional parameters accepted by LSMStore

### ISSUE THREAD

**Issue by paolocappelletti** [HorizenOfficial/Sidechains-SDK#187]
`com.horizen.storage.IODBStorageUtil.getStorage`  method should accept also the other optional parameters accepted by LSMStore class (see [here](https://github.com/input-output-hk/iodb/blob/0.3.2/src/main/scala/io/iohk/iodb/LSMStore.scala#L43)), and pass them to the underlying constructor.
An application could want to change some of them (the keysize and the keepVersions flag for example).

**Comment by i-Alex** [comment]
Thanks @paolocappelletti! `LSMStore` has some performance and unexpected crash issues. We decided to replace it with LevelDB implementation (see, VersionedLevelDbStorageAdapter). It's already implemented, but still not in dev/master branches.
Regarding the key size, i guess, it should depend on hash function used. So at least for core functionalities it is always the same.
But, probably, for custom logic can be different.
What regarding the `keepVersions` we should consider our consensus algorithm that allows to revert up to 2 consensus epochs, so `keepVersions` value is known and always equal to 1440 (if I'm not wrong). There is no sense to keep more, and theoretically dangerous to keep less.

**Comment by i-Alex** [comment]
Seems not relevant anymore. IODB storage was removed.
