### ISSUE TITLE
move io.horizen.lambo.car.transaction.AbstractRegularTransaction into the SDK?

### ISSUE THREAD

**Issue by paolocappelletti** [HorizenOfficial/Sidechains-SDK#192]
the class [io.horizen.lambo.car.transaction.AbstractRegularTransactio](https://github.com/HorizenOfficial/lambo-registry/blob/master/src/main/java/io/horizen/lambo/car/transaction/AbstractRegularTransaction.java) is a very useful starting point for every custom transaction that requires payment of  a fee: it should be useful to have it directly on the SDK to avoid code duplication between customer projects.

**Comment by i-Alex** [comment]
done
