### ISSUE TITLE
Logs with timestamps

### ISSUE THREAD

**Issue by i-Alex** [HorizenOfficial/Sidechains-SDK#194]
Currently the log file of the SidechainNode doesn't contain timestamps for the printed data.
We should be able to add such possibility.
Probably:
-Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat="yyyy-MM-dd HH:mm:ss:SSS"****
may help.

**Comment by paolocappelletti** [comment]
I changed the log format also by placing a file here (in the sidechain app):
/src/main/java/resources/simplelogging.properties
with a content like this:
org.slf4j.simpleLogger.defaultLogLevel=debug
org.slf4j.simpleLogger.showDateTime=true
org.slf4j.simpleLogger.dateTimeFormat=yyyy-MM-dd HH:mm:ss:SSS Z

and was able to append log messages from the sidechain app with this

    private static Logger log =  LoggerFactory.getLogger(MyApp.class);
    log.debug("...."):

( should be useful to add these to the docs!)

**Comment by i-Alex** [comment]
Done in 0.3.0
