### ISSUE TITLE
parametrize path to sidechains-sdk-scbootstrappingtools-0.2.2.jar inside SidechainTestFramework 

### ISSUE THREAD

**Issue by paolocappelletti** [HorizenOfficial/Sidechains-SDK#197]
I was able to write inside a user app  a python test that re-uses the SDK SidechainTestFramework to bootstrap the sidechain and performs some custom transactions (will post soon a pull request to lambo-registry with an example of that!). 
But in order to execute it correclty from the user application we need to parametrize this line of code, allowing to define an absolute path for the SDK itself, to find the bootstrap jar
https://github.com/HorizenOfficial/Sidechains-SDK/blob/master/qa/SidechainTestFramework/scutil.py#L101

proposed solution:

```
 java_ps = subprocess.Popen(["java", "-jar",
       os.getenv("SIDECHAIN_SDK", "../") + "/tools/sctool/target/sidechains-sdk-scbootstrappingtools-0.2.2.jar",
       command_name, json_param], stdout=subprocess.PIPE)
```

**Comment by paolocappelletti** [comment]
Please also change the default tmp dir here:
https://github.com/HorizenOfficial/Sidechains-SDK/blob/master/qa/SidechainTestFramework/sc_test_framework.py#L116
with something more generic not containing the 'simpleapp' name
proposed:
parser.add_option("--tmpdir", dest="tmpdir", default="./tmp",   help="Root directory for datadirs")

**Comment by paolocappelletti** [comment]
added branch https://github.com/HorizenOfficial/Sidechains-SDK/tree/issue_197 with the proposed implementation

**Comment by i-Alex** [comment]
@paolocappelletti can you check if this issue is still relevant? If not, feel free to close it.
