### ISSUE TITLE
documentation: use same dictionary as zen-cli and Sphere in the sc_create parameter list

### ISSUE THREAD

**Issue by paolocappelletti** [HorizenOfficial/Sidechains-SDK#200]
inside the workflow example doc
https://github.com/HorizenOfficial/Sidechains-SDK/blob/master/examples/simpleapp/mc_sc_workflow_example.md
we should better clarify  in step 7 that these 3 parameters of sc_create:

- Verification key from step 4 ("5e7...000") - That key is used for verifying backward transfers, verification file shall contains that key in byte form
- Vrf public key ("dd2...000") - that key was generated by generateVrfKey command on step 3
- GenSysConstant ("b86...000") - it was generated on step 4

have these names inside the zen-cli help and inside  the Sphere  creation form:
- wCertVk
- custom data
- constant data

**Comment by tamkgkgkg** [comment]
Hj
