### ISSUE TITLE
NodeWallet interface should expose a method to add a new secret

### ISSUE THREAD

**Issue by paolocappelletti** [HorizenOfficial/Sidechains-SDK#227]
the NodeWallet interface exposes only methods to list the wallet secrets.
Should also expose a method to add a new one.

Example of usecase that needs it:
we want to add a custom endpoint to import a private key inside the current node wallet.
The endpoint handler can access the node wallet using SidechainNodeView.getNodeWallet() but without the add method cannot import the key.

alternative: add  the importKey endpoint to the ones provided by default by the sdk

**Comment by i-Alex** [comment]
Done
