### ISSUE TITLE
Certificate submission process optimization

### ISSUE THREAD

**Issue by i-Alex** [HorizenOfficial/Sidechains-SDK#256]
In current SDK version (`dev` branch) there is an inefficient trigger for certificate creation and submission to the MC.
Creation attempt is triggered by chain tip update on SC side.
When the new tip arrived the following certificate submission logic is performed:
1) Check that the tip belongs to the certificate submission logic. If not -> break
2) Check that the new certificate quality is greater then the top quality cert synced back to the sidechain (if exists). If less or equal -> break
3) Generate snark proof.
4) Send to the MC via websocket.

Such a flow is inefficient and leads to the unnecessary proofs generation that costs a lot, because:
a) Submitter doesn't consider certificates in the MC mempool
b) Submitter doesn't consider certificates already applied to the MC chain, but not yet synced back as a part of a SC block.
c) Submitter doesn't cache the proof for a given withdrawal epoch in case of, for example, fork chains certificates race.

I suggest to add the new request type to the MC websocket server `GetCertificateStatus(scId: String)` that will return the info about the top quality cert stored in the chain and the top quality cert contained in the mempool for given `scId`. Both are optional. Info entry consists of `certHash`, `rawCertificateHex`, `fees` (optional, for mempool entry).

Certificate Submitter on step (2) will use the new request type to check if there is already a proper certificate present in the MC mempool or chain and will decide to generate or not another one with a specific fees in case of sc forks race. Moreover, Submitter should cache the previously generated certificate data (including the snark proof) and should reuse them if need.

**Comment by i-Alex** [comment]
As was discussed AFK, don't use the cache for the proofs, because with the current approach in will be reused only in a very extreme cases, like MC fork for a specific MC block (last withdrawal epoch block) or Cert revert because of the inputs conflicts. We can avoid adding such a complexity to the code.

Also to have more optimized solution, we should add additional trigger for cert generation attempt -> new MC tip event. Which is used only after the last withdrawal epoch SC block arrived. The flow remains the same as proposed.

**Comment by Jamesarmy1993** [comment]
❤️
