### ISSUE TITLE
Reader.remaining usage

### ISSUE THREAD

**Issue by albertog78** [HorizenOfficial/Sidechains-SDK#36]
Actual parsing implementation rely on number of bytes returned by the remaining method to validate input data (eg. if we expect to read X bytes we check if remaining returns at least X). If Reader implementation is reading from a stream, could be that current remaining data is less than data that can be read from stream. This will lead to not properly parse the whole data. 
"remaining" method description is the following:
/**
    * Returns the number of elements between the current position and the
    * end of Reader
    * @return The number of elements remaining in th Reader
    */

It would be useful to clarify the real meaning of the number returned by this method (if means  the number of bytes that can be read without blocking or if it means the whole data that can be read before reaching the end of the stream).

**Comment by i-Alex** [comment]
Current issue will be solved as a part of solution for https://github.com/ZencashOfficial/Sidechains-SDK/issues/88.
