### ISSUE TITLE
Block detail: inconsistency between weboscket event and api endpoint 

### ISSUE THREAD

**Issue by paolocappelletti** [HorizenOfficial/Sidechains-SDK#365]
there is an inconsistency between data returned in the 
**single_block** / **new_single_block** websocket event 
and data returned in 
/block/findById  http endpoint

In the first one is missing the blockHex
In the second one is missing the (new) feePayments  list,  the height of the block and the hash

the object in the websocket is: 

```
{
   block,
   height,
   hash,
   feePayments?
}
```

and in the endpoint: 
```
{
   blockHex,
   block
}
```

(reported by Thomas)

**Comment by i-Alex** [comment]
`height` in API response was added in PR https://github.com/HorizenOfficial/Sidechains-SDK/pull/328
`feePayments` was not planned to add to API and I'm not sure that we need it.

**Comment by paolocappelletti** [comment]
I think feePayments should be added, can be very useful for debugging or later inspection to know exaclty all the boxes that appeared in a specific block, including this ones.

**Comment by otoumas** [comment]
Also, adding the block hex to the socket message payload would be really useful in the explorer
