### ISSUE TITLE
improve websocket configuration

### ISSUE THREAD

**Issue by paolocappelletti** [HorizenOfficial/Sidechains-SDK#382]
The websocket is configured in this section of the config file:

websocket {
         address = "ws://localhost:8888"
        connectionTimeout = 100 milliseconds
        reconnectionDelay = 60 seconds
        wsServer = false
        wsServerPort = 8025
}

we have the following problems:
- is not possible to disable the websocket connection to the ZEND node (could be useful if I want to just sync my node with other sidechain nodes without forging)
- if **connectionTimeout** and **reconnectionDelay**  have big values (like in the example above) and the zend is not available, the node gets stuck trying and retrying to connect to it, nothing is logged in the log and the API endpoints are not responding
- it is not clear that wsServer and wsServerPort  are used to configure an incoming websocket used by the explorer (maybe a better name?)

**Comment by i-Alex** [comment]
Point 1 was described here: https://github.com/HorizenOfficial/Sidechains-SDK/issues/353
Point 3 was described here: https://github.com/HorizenOfficial/Sidechains-SDK/issues/352

Point 2 is a new one.

**Comment by i-Alex** [comment]
The missing point was put here: https://horizenlabs.atlassian.net/browse/SDK-938
