### ISSUE TITLE
Inconsistnecy in SidechainHistoryStorage

### ISSUE THREAD

**Issue by oaleksandrov-ip** [HorizenOfficial/Sidechains-SDK#41]
SidechainHistoryStorage shall always use the active chain for all requests, i.e.
  _def height: Int = heightOf(bestBlockId).getOrElse(0)_
to
  _def height: Int = activeChain.height_

also refactoring shall be done to removing active chain null checking:
  _def blockInfoById(blockId: ModifierId): Option[SidechainBlockInfo] = {
    if (activeChain != null && activeChain.contains(blockId))
      return activeChain.blockInfoById(blockId)_

**Comment by i-Alex** [comment]
Done
